name: Build and Deploy to Cloud Run

on:
    push:
        branches:
            - master

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    RUN_REGION: us-central1
    SERVICE_NAME: super-simple-service

jobs:
    setup-build-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4  # Updated to latest version

            # Setup gcloud CLI using the correct GitHub Action
            - uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ secrets.PROJECT_ID }}
                  service_account_email: ${{ secrets.SA_EMAIL }}
                  service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

            # Configure gcloud CLI
            - name: gcloud Set up
              run: |
                  gcloud config set project $PROJECT_ID
                  gcloud auth configure-docker gcr.io

            # Build and push image to Google Container Registry
            - name: Build
              run: |
                  gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

            # Deploy image to Cloud Run
            - name: Deploy
              run: |
                  gcloud run deploy $SERVICE_NAME \
                    --region $RUN_REGION \
                    --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
                    --platform managed
